In [1]:
import requests

In [2]:
URL="https://stephen-king-api.onrender.com/api/books"
res=requests.get(URL)

In [3]:
json_data=res.json()

In [4]:
import pandas as pd
df=pd.json_normalize(json_data["data"])

In [5]:
df=df[["Year","Title","Publisher","ISBN"]]
df

    Year            Title        Publisher                  ISBN
0   1974           Carrie        Doubleday     978-0-385-08695-0
1   1975      Salem's Lot        Doubleday     978-0-385-00751-1
2   1977      The Shining        Doubleday     978-0-385-12167-5
3   1977             Rage     Signet Books     978-0-451-07645-8
4   1978        The Stand        Doubleday     978-0-385-12168-2
..   ...              ...              ...                   ...
59  2018        Elevation         Scribner     978-1-98210-231-9
60  2019    The Institute         Scribner     978-1-98211-056-7
61  2021            Later  Hard Case Crime     978-1-78909-649-1
62  2021    Billy Summers         Scribner     978-1-982-17361-6
63  1979  The Roopak Zone     Viking Press  978-0-670-26069697-5

[64 rows x 4 columns]

In [6]:
#Web scraping
import requests
URL="https://www.scrapethissite.com/pages/simple/"
res=requests.get(URL)

In [7]:
print(res.status_code)

200

In [17]:
if res.status_code==200:
     # print(res.text)#content of the html in string
     # print(res.content)#raw content
     print(res.headers)#metadata relate data

{'Date': 'Tue, 18 Aug 2026 11:34:39 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=VfjoaiiFOAUV0q0RCCyD0SJ5A8Ipp0BqBcxAXsxpQcY%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1787052879"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=VfjoaiiFOAUV0q0RCCyD0SJ5A8Ipp0BqBcxAXsxpQcY%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1787052879"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': 'a2d09c4e7fb4ea90-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [9]:
# if res.status_code==200:
#     print(res.headers) 
with open("scraped_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

In [10]:
!pip install lxml

Requirement already satisfied: lxml in C:\Users\mehar\anaconda3\Lib\site-packages (6.1.1)

In [13]:
#BeautifulSoup
import sys
!{sys.executable} -m pip install lxml
from bs4 import BeautifulSoup
with open("scraped_data/data1.html", "r") as f:
    html_content=f.read()
soup=BeautifulSoup(html_content,"lxml")

Requirement already satisfied: lxml in C:\Users\mehar\anaconda3\Lib\site-packages (6.1.1)

In [16]:
soup.find("h3")

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [31]:
all_h3=soup.find_all("h3")
all_countries=[]
for h3 in all_h3:
    name=h3.get_text(strip=True)
    parent=h3.find_parent()
    cls=h3.find_parent()["class"]
    population=h3.find_next("div").select("span.country-population")[0].get_text()
    population1=h3.find_next("div").select_one("span.country-population").get_text()
    
    all_countries.append([name,population])

In [33]:
import pandas as pd
df=pd.DataFrame(all_countries,columns=["Name","Population"])

In [34]:
df

                        0         1
0                 Andorra     84000
1    United Arab Emirates   4975593
2             Afghanistan  29121286
3     Antigua and Barbuda     86754
4                Anguilla     13254
..                    ...       ...
245                 Yemen  23495361
246               Mayotte    159042
247          South Africa  49000000
248                Zambia  13460305
249              Zimbabwe  11651858

[250 rows x 2 columns]

In [35]:
df.to_csv("cleaned_data/data.csv",index=False)

In [ ]:
#Navigating DOM
parent=h3.parent
child=h3.children
descendents=h3.descendents
next_sibling=h3.next_sibling()
previous_sibling=h3.previous_sibling()