In [2]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [3]:
insurance= pd.read_csv("insurance.csv")
insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
#One Hot encoding
X = insurance.drop(columns=["charges"])
Y = insurance["charges"]

X= pd.get_dummies(X, columns=["region"], drop_first=True, dtype=int)

X["sex"]= X["sex"].map({"female": 1 ,"male": 0})
X["smoker"]= X["smoker"].map({"yes": 1 ,"no": 0})

In [5]:
X.sample(10)

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
1304,42,0,24.605,2,1,0,0,0
285,46,0,26.620,1,0,0,1,0
1219,38,1,30.210,3,0,1,0,0
261,20,1,26.840,1,1,0,1,0
679,49,1,23.180,2,0,1,0,0
800,42,1,26.180,1,0,0,1,0
933,45,1,35.300,0,0,0,0,1
299,48,1,28.880,1,0,1,0,0
890,64,1,26.885,0,1,1,0,0
553,52,1,31.730,2,0,1,0,0

In [6]:
#y_pred

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)

In [8]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test, y_pred)
print("r^2 val: ",r2)

n = X_test.shape[0]
p = X_test.shape[1]


adj_r2 = 1-((1-r2)*(n-1)/(n-p-1))
print("adj val: ", adj_r2)

r^2 val:  0.7835929767120724
adj val:  0.7769085898923681

In [9]:
#Interaction feature
X = insurance.drop(columns=["charges"])
Y = insurance["charges"]

X= pd.get_dummies(X, columns=["region"], drop_first=True, dtype=int)

X["sex"]= X["sex"].map({"female": 1 ,"male": 0})
X["smoker"]= X["smoker"].map({"yes": 1 ,"no": 0})

X["age_smoker"]= X["age"]*X["smoker"]
X["bmi_smoker"]= X["bmi"]*X["smoker"]

In [10]:
X.sample(10)

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
411,44,1,20.235,1,1,0,0,0,44,20.235
319,32,0,37.335,1,0,0,0,0,0,0.000
223,19,0,34.800,0,1,0,0,1,19,34.800
1172,56,1,41.910,0,0,0,1,0,0,0.000
595,46,1,33.725,1,0,0,0,0,0,0.000
930,26,0,46.530,1,0,0,1,0,0,0.000
105,20,0,28.025,1,1,1,0,0,20,28.025
479,23,0,32.560,0,0,0,1,0,0,0.000
660,37,0,46.530,3,0,0,1,0,0,0.000
82,22,0,37.620,1,1,0,1,0,22,37.620

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)

In [12]:
r2 = r2_score(Y_test, y_pred)
print("r^2 val: ",r2)

n = X_test.shape[0]
p = X_test.shape[1]


adj_r2 = 1-((1-r2)*(n-1)/(n-p-1))
print("adj val: ", adj_r2)

r^2 val:  0.865231697953168
adj val:  0.8599877951497893

In [13]:
y_train_pred=model.predict(X_train)

r2_train = r2_score(Y_train, y_train_pred)
print("r^2 train val: ",r2_train)
print("r^2 val: ",r2)

r^2 train val:  0.8340713711218875
r^2 val:  0.865231697953168